pkg<-c("gridExtra","lattice","imputeMissings","RANN","corrplot","nnet","car",
       "gpairs","reshape2","psych","plyr","DT","CORElearn")
install.packages(pkg)
install.packages("shiny")
install.packages("vcd")
install.packages("multcomp")
install.packages("glmnet")
install.packages("maps")
install.packages("ggmap")
install.packages("XML")
install.packages("testthat")
install.packages("roxygen2")
install.packages("leaflet")
install.packages("dygraphs")
install.packages("DiagrammeR")
install.packages("networkD3")
install.packages("threejs")
install.packages("lubridate")
install.packages("dplyr")
install.packages("tidyr")
install.packages("xlsx")
install.packages("flexdashboard")
install.packages("profvis")

pkg<-c("readr","rvest","plyr","listviewer","googleVis","metricsgraphics",
       "plotly","choroplethr","tmap","rga","roxygen2","RSiteCatalyst","openxlsx","scales","captioner",
       "proxy","XLConnect","readxl","tiff","jpeg","png","RColorBrewer","mallet")

p_needed <- c("plyr", "dplyr", "stringr", "lubridate", "jsonlite", "httr", "xml2", "rvest", "devtools", "ggmap",  "networkD3", "RSelenium", "pageviews", "aRxiv", "twitteR", "streamR")
lapply(p_needed, require, character.only = TRUE)
library(pageviews)
library(lubridate)
library(dygraphs)
library(xts)
library(leaflet)
install.packages(pkg)
install.packages("tm")
install.packages("wordcloud")
install.packages("memoise")
library(devtools)
devtools::install_github('Ather-Energy/ggTimeSeries')
install.packages("DT")
