# Self-development
## Emotion Management

### Emotional First Aid (情绪急救)

> Dr. Guy Winch is a licensed psychologist, author, and in-demand keynote speaker whose books have been translated into 24 languages. His first TED Talk, Why We All Need to Practice Emotional First Aid has been viewed over 5 million times and is rated as the #5 most inspiring TED Talk of all time on ted.com He also writes the popular Squeaky Wheel Blog on Psychology Today.com (https://www.psychologytoday.com/blog/the-squeaky-wheel) and he has dabbled in stnad-up comedy. His website is www.guywinch.com. You can view his TED Talks here: https://www.ted.com/speakers/guy_winch

Healing Rejection, Guilt, Failure, and Other Everyday Hurts

### How To Keep People From Pushing Your Buttons

> About the author: Albert Ellis(1913-2007) held M.A and Ph.D. degrees in Clinical Psychology from Columbia University. He was the founder of Rational Emotive Behavior Therapy (REBT), the pioneering form of the modern Cognitive Behavior therapies. He was the president of the Albert Ellis Institute in New York, where he practiced individual and group psychotherapy, supervised and trained psychotherapists, and presented many talks and workshops at the Institute and throughout the world. He published over seven hundred articles and more than sixty books on psychotherapy, marital and family therapy, and sex therapy.

4 fatal "Overly":

1. Anxious
1. Angry
1. Depressed
1. Guilty

3 nutty beliefs (Realistic Preferences):

(1) Awfulizing
(2) Shoulding
(3) Rationalization

The three nutty beliefs will further lead to 10 nutty beliefs:

(1) Worry too much about what other people think of you
    - Please others
    - Overly defensive

(2) Excessively fear of failure
    - Lack of risk-taking
    - Stagnation
    - Mediocrity

> If you are hitting the bullseye every time you shoot, you are standing too close!

(3) Low frustration tolerence
    - impulsive reactions, premature quitting, nagativism, avoidance of responsibility, lack of perseverance
    
(4) Blame others

(5) Worry obsessively about things to happen

(6) Perfectionism

(7) Avoid responsibility

(8) Detachment

(9) Blame past experience

(10) Bad things/people shouldn't exist

<!--

Ellis列出了四种不好的过激情绪：
过分的烦躁（紧张、沮丧、恼火、担惊受 怕）；比如你为准备一个工作面试而紧张，为孩子最近的表现而烦躁。
过分生气（戒备、被激怒，气得发疯，挫 败）：当你的配偶批评你不干活，当工作上的同事不配合或做不来时。
过分抑郁（无精打采，一蹶不振）：失去所爰的人，或失去工作。
过分内疚（过分承担责任，过分悔恨，过分自责）：比如你因为离婚而对孩子内疚，处处宠溺。
如何判断过分？其实人们在85%的时间里，是能识别出自己什么时候反应过激。而你要做的就是让尽可能多的过激反应不要发生。

你的坏情绪是怎么来的？人不是天生就有坏情绪的，Ellis给出了诱因ABC公式。
A代表曰常遇见的人或事情。除了那些重大的事件外，A就是那些烦人的小事，比如难缠的 上司、同事，办公室的勾心斗角，沟通不够； 生活中与配偶或情人的冲突，家务劳动，财务 问题。

C代表在A的情形下你的感觉和行为。如果你有一个重要的会议，但路上大堵车，这时你就会从平时的绅士变成路怒一族，不断并线加塞，嘴里骂骂咧咧。那么真的是堵车导致了你这样的路怒行为了吗？不是的，在A和C之间，有一个B

B就是我们对具体发生的人或 事的思考、判断。

这样你就会明白，不是A这件事一定会产生C的结果，A本身不会导致C，而是B导致了C，A只是诱因。

三类病态的思维模式导致情绪和行为反应过激
恐怖化的思维方式。把什么都看成了灾难，非常害怕，思维模式就是“万一……怎么 办”？比如你去面试一份工作，你可能会想 到：万一我回答不上问题怎么办？万一他们不 喜欢我怎么办？万一我被人难堪了怎么办？越想越多，就越恐慌，你高度紧张，未战而败。

应该化的思维方式。“我必须……’”我一定……“，这种”必须”“应该”的思维可能源自孩提时代，父母说：你应该对弟弟好一点；老师说：你应该五讲四美。一旦有了 “应该”的思维，就会使你对自己要求过于严苛，把自己弄得很惨。当你达到了我应该“的标准时，你就开始了对别人的”你应该”。

合理化的思维方式。这种思维就是认为什么都很合理，不可思议地将不道德或不得体的 行为合理化，骗自己接受这种行为，简单地说 就是逆来顺受。典型的表现就是：谁会关心？ 那又怎样？这种思维方式会把很多不合理的事情也认为是合理的，合理化思维是一种软弱的应对方式。

你如果老是用恐怖化、应该化、合理化去思考 问题的话，就会陷入以下10种非理性人生信条：

信条1:太在乎别人怎么看待你。因为太在乎 会导致你对拒绝的强烈的恐惧感，要么你会四处讨好别人，避免冲突；要么你就把自己装扮 成一只刺猬，逮谁扎谁。其实你更好的选择可以是这样的：“我希望你们喜欢我，尊重我， 你们要是做不到，我也能忍受”。（恐怖化）

信条2:无法忍受在重要任务上失败。如果你让自己相信在任何重大事件上都输不起，你就 不敢冒险，会墨守成规。还有就是无法忍受别人的批评。（恐怖化）

信条3:人和事都应该朝着我要的方向发展。这是由于低耐挫性和对不公平的敏感而造成的 冲动反应，会导致半途而废，逃避责任。（应该化）

信条4:某件事出错了，肯定是有人出了问题。凡事绝对化，认为事情做得那么糟，肯定 是有人不尽力，这些人善于把脏水往别人身上泼。（应该化）

信条5:对即将发生的事情总是抱着深深的忧虑。（恐怖化）

信条6:每个问题都有完美的解决方案，我必须立即找到这些方法。有时候完美主义造就了拖延症。（应该化）

信条7:在很多困境和责任面前可以让自己置身事外，凡事都能找到一个合理化的理由。 (合理化）

信条8:如果事事不投入，保持若即脱离的关注，会永远开心。很多人貌似参与了很多事， 但其实他们只是坐在那儿，被动地观察。（合理化）

信条9:因为过去或者小时候发生的一些不好的事情造成了我现在这个样子，我努力也改变不了。（合理化）

信条10:这些坏人坏事就不应该存在，真不知道拿他们怎么办。他人他事会逼得你反应过激。（应该化）

怎样应对病态的思维方式？
把事情恐怖化、应该化和合理化是三大逼迫我们就范的方式，要我们不去这么想的方法就是 第四种思考模式：你要看看在这三种思维模式 之外有什么是更好的选择，比如“我想 要……，”我更喜欢……“，”如果……就更好了“。它不是必须时刻要积极，并不表明你能够或一定成功，而是说要去试一试，即使可能会失败、被拒绝。

比如你是个演讲新手，但最近你有一场重要的 演讲，你很可能会把前面三类病态思维都用一 下：“万一我搞砸了，没人听，大家聊天会怎 么办？（恐怖化）我应该能够做好公共演讲， 我用不着害怕。（应该化）其实，这有多大的事，就是搞砸了也没人在乎。（合理化）”但如果你能更好的选择思维方式：嗯，我想要做好演讲，但也不是非做好不可，现在还有一点时间，我可以在脑子里再过一次提纲；其实我更喜欢演讲的过程，我想我肯定能从中学到什么。这样你就不会背负心理包袱。

如何让“更好的选择”成为习惯？
改变想法需要觉悟，还有需要用大量的练习建 立起第四种思维模式的习惯‘‘更好的选择“。 有四个步骤：

反思自己的C (感觉和行为）：我的感觉和行为是不是合适？
认真审视自己的B是怎么把自己弄成了C的样子（过分的焦虑、愤怒、抑郁、内疚）
如何反击和对抗自己的非理性思考方式
用什么样的更好选择来替代非理性思维
用“我想要……”，“我喜欢……”，“如果……就更好了”
--!

### Others

- From TED talk: [How to fix a broken heart](https://www.ted.com/talks/guy_winch_how_to_fix_a_broken_heart?utm_source=newsletter_weekly_2018-02-10&utm_campaign=newsletter_weekly&utm_medium=email&utm_content=talk_of_the_week_image)

Heartbreak is far more insidious than we realize. There is a reason we keep going down one rabbit hole after another, even when we know it's going to make us feel worse. Brain studies have shown that the withdrawal of romantic love activates the same mechanisms in our brain that get activated when addicts are withdrawing from substances like cocaine or opioids.

Getting over heartbreak is not a journey. It is a fight, and your reason is your strongest weapon. There is no breakup explanation that is going to feel satisfying. No rationale can take away the pain you feel. So don't search for one. Don't wait for one, just accept the one you were offered or make up one yourself and then put the question to rest, because you need that closure to resist the addition. And you need something else as well: you have to be willing to let go, to accept that it's over. Otherwise, your mind will feed on your hope and set you back. Hope can be incredibly destructive when your heart is broken.