--- 
title: "Reading Notes"
author: "Hui Lin"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
documentclass: krantz
bibliography: [bibliography.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
fontsize: 12pt
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
site: bookdown::bookdown_site
description: "Hui's Reading Notes"
url: 'http\://hui1987.com'
github-repo: happyrabbit/IntroDataScience
---

```{r include=FALSE, echo = FALSE}
# Sys.setenv(TZ="UTC")
options(
  htmltools.dir.version = FALSE, formatR.indent = 2,
  width = 55, digits = 4, warnPartialMatchAttr = FALSE, warnPartialMatchDollar = FALSE
)

# ids_url = function(file) {
#  paste0('https://github.com/',
#         'happyrabbit/DataScientistR/',
#         'raw/master/', file)
# }

#bookdown::render_book("index.Rmd", "bookdown::gitbook")
#bookdown::render_book("index.Rmd", "bookdown::pdf_book")
```

# Introduction

Learning is happening increasingly outside of formal educational settings and in unsupervised environments. Technological advantages provide new tools and opportunities for life-time learners. This reading notes is my first step of managing my learning (aka: Personal Knowledge Management). This step is called Personal Information Management(PIM). The goals are:

1. Organize information
1. Initially process the information and understand the information structure
1. Chunking: cluster similar information, filter out some detail, degrade the complexity

The reading notes are arranged according to book category in my reading list since 2009. For some reason I lost all reading information before 2009. There are tons of paper notes need to be digitized and I will keep working on it in my spare time. My personal comments will start with “Hui:” in blue. Sometimes I summarize the contents with my own words. It is great if you find any of those notes useful for you as well. I thank all my friends who recommended great books to me. I wrote this notes with [R Markdown](https://rmarkdown.rstudio.com)  and the R package [bookdown](https://bookdown.org/yihui/bookdown/).