---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Hui Lin

fontawesome: yes
email: longqiman@gmail.com
github: happyrabbit
# phone: ""
web: scientistcafe.com
updated: no

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Education 

- **2011 - 2013**, PhD in Statistics, Department of Statistics, Iowa State University, USA

- **2009 - 2011**, MS in Statistics, Department of Statistics, Iowa State University, USA

- **2005 - 2009**, BS in Statistics, School of Mathematical Science, Beijing Normal University, CHINA

# Computer Skill:

- Programming:  expertise in R (8 yrs), Python (1+ yr), SQL (4+ yr),  CSS, JavaScript, HTML5
- Software and system: SAS, Linux/Unix, Windows, AWS, limited experience with spark

# Working and Research Experience

- **Sep.2017 - Present**, Data Scientist, DowDuPont, Johnston, IA, USA
    
    - Provide data science leadership for a broad range of analytics in North America Marketing:
        1. Predictive Analytics:  _Bayesian Regression Model, Super Learner ensembles:  Elastic Network Regression,  AIC Stepwise Regression, Random Forest, Neural Network, Support Vector Machine, Gradient Boosting Tree, Partial Least Square Regression_
        2. Marketing programs analysis under the observational scenario: _Provide statistical training to other analysts on experimental design and propensity score analysis_
<br>    
    - Lead the project of building marketing data pipeline:
        1. Build marketing database in the cloud
        2. Automate models and dashboard that track business performance
            - _(1) Identify key marketing metrics with the marketing analytics team_
            - _(2) Develop  and implement Shiny dashboard including those metrics_
        3. Social media analytics 
            - _(1) Construct automatic social media data pipeline with data engineer: scrape data from Ag Forum or get data through API, build database in the cloud, develop dashboard for marketing users_
            - _(2) Network Analysis, Natural Language Processing (POS tagging, entity recognition, sentimental analysis, topic modeling) _

- **May.2013 - Aug.2017**, Data Scientist, DuPont Pioneer, Johnston, IA, USA
    - Provide data science leadership for a broad range of analytics in North America Marketing focused on improving Sales and Marketing productivity 
<br>   
    - Analyze market research survey data using psychometric models and natural language processing; quantitatively study customer perception and identify variables that are predictive of patterns and/or are leading indicators
        - _Factor analysis,  Topic Model, Longitudinal Analysis_
        
    <p>- Work with data engineers to design and build marketing database in the cloud to support current and future marketing analytics
        - _It evolves to the current project on marketing data pipeline_</p>

- **Jun.2015 - Present**, Co-founder, [Central Iowa R User Group](http://www.meetup.com/Central-Iowa-R-User-Group/)

- **Jun.2012 - Apr.2013**, Consultant, Statistical Consulting for Business College, Iowa State University

<!--
- **Apr.2012 - Apr.2013**, Research Assistant, [Exact Test for Difference in Proportions Based on One-to-two Matched Binary Data](http://scientistcafe.com/works/MatchedTestDraft.pdf)

- **Nov.2011 - Apr.2013**, Research Assistant, [Distribution of Non-normal, Dependent Bivariates with Additive Measurement Error](http://scientistcafe.com/works/AME_Draft_Hui_Mar20.pdf)
-->

- **Sep.2009 - Apr.2013**, Statistician, [Production Animal Disease Risk Assessment Program](http://www.padrap.org/)

- **Aug.2011 - May.2012**, Consultant, General University Statistical Consulting and Statistics Consulting for College of Veterinary Medicine, Iowa State University

<!--
- **Spring.2010 Semester**, Teaching Assistant, TA for STAT 341, 342, Department of Statistics, Iowa State University
-->

# Certifications

- **Convolutional Neural Networks** by deeplearning.ai on Coursera. Certificate earned on January 5, 2018

- **Social and Economic Networks: Models and Analysis** by Stanford University on Coursera. Certificate earned on January 3, 2018

- **Programming Foundations with JavaScript, HTML and CSS** by Duke University on Coursera. Certificate earned on November 18, 2017

- **Structuring Machine Learning Projects** by deeplearning.ai on Coursera. Certificate earned on October 20, 2017
    
- **Improving Deep Neural Networks: Hyperparameter tuning, Regularization and Optimization** by deeplearning.ai on Coursera. Certificate earned on October 10, 2017
    
- **Neural Networks and Deep Learning** by deeplearning.ai on Coursera. Certificate earned on September 26, 2017

- **Pioneer Young Professionals Leadership Exploration and Development Program**
    - DuPont Pioneer
    - January 2016 – December 2016

# Book 

- [Machine Learning using R](http://scientistcafe.com/book/): By Hui Lin
    - Publisher: Publishing House of Electronics industry
    - Status: Published in Oct 2017
    - ISBN : 9787121326585
    
- [Introduction to Data Science](http://scientistcafe.com/IDS): By Hui Lin and Ming Li
    - Publisher: CRC Press
    - Status: 2019 Dec 31 (Expected)
    - Github: https://github.com/happyrabbit/IntroDataScience
    
# Book Translation

- [Applied Predictive Modeling](http://appliedpredictivemodeling.com): By Max Kuhn and Kjell Johnson
    - Chinese translator for chapters 1-4, 12-14, 16, 18-20
    - Pubisher in China: Huazhang Publishing Inc.
    - Status: Published in May 2016

- [R for Marketing Research and Analytics](http://r-marketing.r-forge.r-project.org): By Chris Chapman and Elea McDonnell Feit
    - Chinese translator for the book
    - Pubisher in China: Huazhang Publishing Inc.
    - Status: Published in Oct 2016

- [Statistical Rethinking - A Bayesian Course with Examples in R and Stan](http://xcelab.net/rm/statistical-rethinking/): By Richard McElreath
    - Chinese translator for the book
    - Pubisher in China: Huazhang Publishing Inc.
    - Status: Expect to finish by May 2018

# Journal Publications

- **Hui Lin** (2017.11), [How to be a data scientist?](http://blog.csdn.net/heyc861221/article/details/78438677), Programmer, China Software Developer Network

- Krysta Deitz, Kelly Makielski, Jackie M. Williams, **Hui Lin**, Jo Ann Morrison (2015). [Effect of 6-8 weeks of oral ursodeoxycholic acid administration on serum concentrations of fasting and postprandial bile acids and biochemical analytes in healthy dogs](http://www.ncbi.nlm.nih.gov/pubmed/26274488),Veterinary Clinical Pathology, DOI: 10.1111/vcp.12275. 

- **Hui Lin** (2013), [Statistical methods in disease risk analysis, disease testing and nutrition epidemiology](http://lib.dr.iastate.edu/etd/13380), Graduate Theses and Dissertations. Paper 13380. 

- Holtkamp D.J., **Lin H.**, Wang C, Polson D.D. (2013), [Evaluation of an objective risk scoring system for assessing the likelihood of virus introduction in porcine reproductive and respiratory syndrome virus-free breed-to-wean sow herds in the U.S.](http://www.scirp.org/journal/PaperInformation.aspx?PaperID=32700) Open Journal of Veterinary Medicine. 3 168-175.

- **Hui Lin**, Chong Wang, Peng Liu, Derald J. Holtkamp (2012), [Construction of Disease Risk Scoring Systems using Logistic Group Lasso: Application to Porcine Reproductive and Respiratory Syndrome Survey Data](http://www.tandfonline.com/doi/abs/10.1080/02664763.2012.752449), Journal of Applied Statistics. DOI:10.1080/02664763.2012.752449 
   
- Derald J. Holtkamp, **Hui Lin**, Chong Wang (2012), [Identifying questions in the American Association of Swine Veterinarian's PRRS risk assessment survey that are important for retrospectively classifying swine herds according to whether they reported clinical PRRS outbreaks in the previous 3 years.](http://www.ncbi.nlm.nih.gov/pubmed/22475927), Preventive Veterinary Medicine 106(2012) 42-52

- Allen, Kelli; Coetzee, Johann; Edwards-Callaway, Lily; Glynn, Hayley; Dockweiler, Jenna; KuKanich, Butch; **Lin, Hui**; Wang, Chong; Fraccaro, Elena; Jones, Meredyth; Bergamasco, Luciana (2012), [The impact and effect of timing of oral meloxicam administration on physiological responses in calves after dehorning with local anesthesia](http://www.journalofdairyscience.org/article/S0022-0302(13)00403-7/abstract), Journal of Dairy Science, DOI: http://dx.doi.org/10.3168/jds.2012-6251

- **Hui Lin**, Cheng Hao, Xiao Wang, Qiang Yuan, Tong-Jie Zhang, and Bao-Quan Wang (2008), [Observational H(z) Data as a complementary to other cosmological probes](http://www.worldscientific.com/doi/abs/10.1142/S0217732309030217), Modern Physics Letter A (No. MPLA-D-08-00168R1)

<!--
# Technical Reports

- (2014) [Exact Test for Difference in Proportions Based on One-to-two Matched Binary Data](http://scientistcafe.com/works/MatchedTestDraft.pdf)

- (2014) [Distribution of Non-normal, Dependent Bivariates with Additive Measurement Error](http://scientistcafe.com/works/AME_Draft_Hui_Mar20.pdf)

- (2012) [Modeling Dependence with Copulas: Theory and Applications](http://scientistcafe.com/works/ModelingDependence_with_Copulas_TheoryApplications.pdf)
-->

# Tutorials and Invited Talks

- Preparing Statistician to be Successful Big Data Scientist, 2018-06-14, [2018 ICSA Applied Statistics Symposium](http://www.icsa.org/icsa_login/symposium2018/main.html), New Brunswick, NJ

- [Bridging Statistics and Data Science](http://www.cvent.com/events/joint-research-conference/custom-37-2bf39a1d96194e5584e2d22a70df0c31.aspx), 2018-06-11, Joint Research Conference, Santa Fe, NM

- Marketing Data Science, 2018-3-23, The University of Iowa, [Slides](http://scientistcafe.com/IDS/slides/MarketingDataScience.html)

- How to be a data scientist, 2017-12-27, [DATAGURU](http://club.dataguru.cn/activity-view-27.html), [Slides](https://github.com/happyrabbit/Talks/tree/master/DATAGURU2017_12_27)

- Introduction to Data Science, 2017-11-29, American Statistical Association, [Slides](https://github.com/happyrabbit/Talks/tree/master/ASA_SSPA2017_11_29)

- Preparing Statistician/Statistics Graduates to Be Data Scientist, 2017-07-30,
[Joint Statistical Meeting 2017](https://ww2.amstat.org/meetings/jsm/2017/onlineprogram/ActivityDetails.cfm?SessionID=214069), [Course Website](https://github.com/happyrabbit/CE_JSM2017)

- Interactive document and dashboard using R and shiny, 2017-07-12,
[Central Iowa R User Group](http://www.meetup.com/Central-Iowa-R-User-Group/),
[Blog](http://scientistcafe.com/post/MarkdownReport.html)

- Data Scientist Using R - Data Wrangling, 2017-05-02, [Central Iowa R User Group](http://www.meetup.com/Central-Iowa-R-User-Group/), [Blog](http://scientistcafe.com/2017/04/30/DataWrangling.html)

- Data Science Introduction, 2017-03-29,
[Central Iowa R User Group](http://www.meetup.com/Central-Iowa-R-User-Group/),
[Slides](http://linhui.org/Hui's_files/DataScientist1.html#(1))

- Unlock Unstructured Data, 2016-12-29,
[Beijing Institute of Technology](https://en.wikipedia.org/wiki/Beijing_Institute_of_Technology),
[Slides](http://hui1987.com/Presentations/UnlockUnstrDataMkt.html#(1)), 
[Rcode](https://github.com/happyrabbit/BTI2016_12_29/tree/master/Rcode)

- Market Research Customer Perception Analytics, 2016-7-21, [Video](https://youtu.be/joajST7JByo), [Slides](http://hui1987.com/Presentations/AirlineSurvey_XueQing/AirlineSurveyPerception.html#(1)), [Rcode](http://hui1987.com/Presentations/AirlineSurvey_XueQing/Rcode.R)

- Data Wrangling in R and Model Technique, 2016-6-8, Capital of Statistics(COS)-North America, [Video](https://www.youtube.com/watch?v=fsHgJhOYOTM), [Slides](http://hui1987.com/Presentations/COS_NA2016-6-8/Presentation_2016_6_8.html), [Rcode1](http://hui1987.com/Presentations/COS_NA2016-6-8/Rcode1.R), [Rcode2](http://hui1987.com/Presentations/COS_NA2016-6-8/Rcode2.R)

- General Process of Data Analysis and Data Preprocessing, 2016-6-2, Capital of Statistics(COS) - North America, [Video](https://www.youtube.com/watch?v=N5iWmpTtxTw), [Slides](http://hui1987.com/Presentations/COS_NA2016-6-2/Presentation_2016_6_2.html), [Rcode](http://hui1987.com/Presentations/COS_NA2016-6-2/Rcode.R)

- [Jewels Academy Math Camp](http://scientistcafe.com/Presentations/MathCamp2016_2_20.html), 2016.2.20, [Jewels Academy](http://jewelsacademy.com/home.html), Des Moines, Iowa

- [What is data scientist](http://scientistcafe.com/2015/12/12/WhatIsDataScientist.html), 2015.12.12, [Capital of Statistics(COS)](http://cos.name/2015/12/20151212salon/), Beijing, CHINA, [Video](http://www.xueqing.tv/course/55),  
[Slides](http://hui1987.com/Presentations/WhatIsDataScientistCOS_2015_12_12.html)

- [Data Pre-processing Using R](http://scientistcafe.com/2015/10/28/DataPre-processingUsingR.html), 2015.11, [Central Iowa R User Group](http://www.meetup.com/Central-Iowa-R-User-Group/),  Johnston, Iowa, USA

- Analytics to Support Business Decision in Traditional Industry, 2014, 7th R conference, Beijing, CHINA

# Services and Professional Membership

- **Program Committee**: Annual Data Institute Conference 2019
- **2018 Program Chair**: ASA Section on Statistics in Marketing
- **2017 Program Chair-Elect**: ASA Section on Statistics in Marketing
- **2016-2017**, Web developer and maintainer,[Johnston Alternative Gift Market](http://www.johnstonagm.org) 
- **2015-Present**, ASA Section on Statistics in Marketing
- **2012-Present**, [Capital of Statitics](http://cos.name/), administrator
- **2012-Present**, Referee, Journal of Applied Statistics
- **2011-Present**, American Statistical Association (ASA), member 
- **May 24-25, 2014**, Committee member, 7th R conference, Beijing, CHINA
- **2013-2014**, Chinese teacher, Iowa Chinese Language School (ICLS), Johnston, Iowa 
    - [ICLS](http://www.iowachineseschool.org/) is a non-profit and volunteer-based organization established on July
17, 1999.

<!--
- **Summer 2007**, Organizer, Campaign to raise money for impoverished students, Shaowu City, Fu Jian Province, CHINA 
-->


