---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Hui Lin

fontawesome: yes
email: hui@linhui.org
github: happyrabbit
# phone: ""
web: scientistcafe.com
updated: no

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Work and Research Experience

- **Sep.2021 - Present, Staff Data Scientist, Shopify**, Seattle, WA, USA 
- **Jul.2020 - Sep.2021, Quantitative UX Researcher, Google**, Mountain View, CA, USA 
- **May.2018 - Jun.2020, Head of Data Science, Netlify**, San Francisco, CA, USA
- **May.2013 - Apr.2018, Marketing Data Scientist (Tech Lead), DuPont**, Johnston, IA, USA 
- **Sep.2009 - Apr.2013, Statistic Consultant and Research Assistant, Iowa State University**, Ames, IA, USA

# Education 

**PhD in Statistics, 2009-2013**,  Iowa State University

- Advisors: Chong Wang and Alicia Carriquiry
- Dissertation: "Statistical methods in disease risk analysis, disease testing and nutrition epidemiology"

**BS in Statistics, 2005-2009**, Beijing Normal University

# Book 

- [Practitioner’s Guide to Data Science](https://www.routledge.com/Practitioners-Guide-to-Data-Science/Lin-Li/p/book/9780815354390): By Hui Lin and Ming Li
    - Publisher: CRC Press
    - Status: Published in May 2023
    - Github: https://github.com/happyrabbit/IntroDataScience

- [Machine Learning using R](http://scientistcafe.com/book/): By Hui Lin
    - Publisher: Publishing House of Electronics industry
    - Status: Published in Oct 2017
    - ISBN : 9787121326585
    
# Book Translation

- [Statistical Rethinking - A Bayesian Course with Examples in R and Stan](http://xcelab.net/rm/statistical-rethinking/): By Richard McElreath
    - Chinese translator for the book
    - Pubisher in China: Huazhang Publishing Inc.
    - Status: Published in Apr 2019
    
- [Applied Predictive Modeling](http://appliedpredictivemodeling.com): By Max Kuhn and Kjell Johnson
    - Chinese translator for chapters 1-4, 12-14, 16, 18-20
    - Pubisher in China: Huazhang Publishing Inc.
    - Status: Published in May 2016

- [R for Marketing Research and Analytics](http://r-marketing.r-forge.r-project.org): By Chris Chapman and Elea McDonnell Feit
    - Chinese translator for the book
    - Pubisher in China: Huazhang Publishing Inc.
    - Status: Published in Oct 2016

# Courses and Invited Talks

- [Programming for Data Science](https://jsm2023.scientistcafe.com/), 2023-08-08, JSM 2023
- [Data Science in Practice](https://course2022.scientistcafe.com/course-syllabus/), 2022-06-13, 2022 Quality and Productivity Research conference

- [User-centered metrics](https://scientistcafe.com/2021/07/14/usercenteredmetrics.html), 2021-07-01, invited by [HyVee](https://en.wikipedia.org/wiki/Hy-Vee) Analytics Team, [Slides](https://scientistcafe.com/talks/2021_06usermetric/usermetric#/)

- [Introduction to Deep Learning (in R and Python)](https://smi2021.scientistcafe.com/)
    - 2021-05-17, The Statistical Methods in Imaging Conference 2021
- [Introduction to Data Science, Machine Learning and Deep Learning (in R and Python)](https://course2021.scientistcafe.com/course-syllabus/)
    - 2021-04-24, SCASA 40th Annual Applied Statistics Workshop
    - 2021-06-26, ASA Council of Chapters Traveling Course [Orange county-long beach]
    - 2021-07-23, ASA Council of Chapters Traveling Course [Nevada]
    - 2021-08-06, ASA Council of Chapters Traveling Course [Georgia]
    - 2021-08-20, ASA Council of Chapters Traveling Course [Columbus]
    - 2021-09-16, ASA Council of Chapters Traveling Course [Middle Tennessee]
    - 2021-10-09, ASA Council of Chapters Traveling Course [Boston]
    - 2021-10-23, ASA Council of Chapters Traveling Course [New York]
- Big Data, Data Science and Deep Learning for Statistician
    - 2019-02-14, 2019 ASA Conference on Statistical Practice, New Orleans, LA
    - 2019-03-24, ENAR 2019 Spring Meeting, Philadelphia
    - 2019-05-15, 33rd New England Statistics Symposium (NESS), Hartford, CT
    - 2019-05-18, ASA Council of Chapters Traveling Course [Snake River Chapter]
    - 2019-06-08, ICSA 2019 Applied Statistics Symposium, Raleigh, NC
    - 2019-07-27, JSM 2019, Denver, CO
    - 2019-09-07, ASA Council of Chapters Traveling Course [Wisconsin Chapter]
    - 2019-09-14, ASA Council of Chapters Traveling Course [Indiana Chapter]
    - 2019-09-28, ASA Council of Chapters Traveling Course [Oregon Chapter]
    - 2019-10-19, ASA Council of Chapters Traveling Course [San Diego Chapter]

- How To Find A Career Path In Data Science, 2019, ODSC West, San Francisco, CA, [Slides](https://scientistcafe.com/talks/odsc2019west/#(1))

- Data Science and Deep Learning for Statisticians, 2019-04-25, Innovations in Design, Analysis, and Dissemination: Frontiers in Biostatistical Methods, Kansas City

- Use blogdown + Netlify to build and deploy your website, 2019-04-18, Bay Area UseR Group, Mountain View, CA
    
- Bridging Statistics and Data Science, 2018-10-03, Fall Technical Conference, West Palm Beach, FL

- Preparing Statistician to be Successful Big Data Scientist, 2018-06-14, 2018 ICSA Applied Statistics Symposium, New Brunswick, NJ

- Bridging Statistics and Data Science, 2018-06-11, Joint Research Conference, Santa Fe, NM

- Marketing Data Science, 2018-3-23, The University of Iowa, [Slides](http://scientistcafe.com/IDS/slides/MarketingDataScience.html)

- Introduction to Data Science, 2017-11-29, American Statistical Association

- Preparing Statistician/Statistics Graduates to Be Data Scientist, 2017-07-30,
Joint Statistical Meeting 2017, [Course Website](https://github.com/happyrabbit/CE_JSM2017)

- Interactive document and dashboard using R and shiny, 2017-07-12,
Central Iowa R User Group,
[Blog](http://scientistcafe.com/post/MarkdownReport.html)

- Data Scientist Using R - Data Wrangling, 2017-05-02, Central Iowa R User Group, [Blog](http://scientistcafe.com/2017/04/30/DataWrangling.html)

- Data Science Introduction, 2017-03-29,
Central Iowa R User Group,
[Slides](http://linhui.org/Hui's_files/DataScientist1.html#(1))

- Unlock Unstructured Data, 2016-12-29,
[Beijing Institute of Technology](https://en.wikipedia.org/wiki/Beijing_Institute_of_Technology),
[Slides](https://scientistcafe.com/talks/2016_12_19_UnlockUnstrDataMkt.html), 
[Rcode](https://github.com/happyrabbit/BTI2016_12_29/tree/master/Rcode)

- Market Research Customer Perception Analytics, 2016-7-21

- Data Wrangling in R and Model Technique, 2016-6-8, Capital of Statistics(COS)-North America

- General Process of Data Analysis and Data Preprocessing, 2016-6-2, Capital of Statistics(COS) - North America

- Data Pre-processing Using R, 2015.11, Central Iowa R User Group  Johnston, Iowa, USA

- Analytics to Support Business Decision in Traditional Industry, 2014, 7th R conference, Beijing, CHINA

# Journal Publications

- **H Lin**, A Zhu, C Wang (2024), [Statistical Tests for Proportion Difference in One-to-Two Matched Binary Diagnostic Data: Application to Environmental Testing of Salmonella in the United States](https://www.mdpi.com/2227-7390/12/5/741), Mathematics 12 (5), 741

- Krysta Deitz, Kelly Makielski, Jackie M. Williams, **Hui Lin**, Jo Ann Morrison (2015). [Effect of 6-8 weeks of oral ursodeoxycholic acid administration on serum concentrations of fasting and postprandial bile acids and biochemical analytes in healthy dogs](http://www.ncbi.nlm.nih.gov/pubmed/26274488),Veterinary Clinical Pathology, DOI: 10.1111/vcp.12275. 

- **Hui Lin** (2013), [Statistical methods in disease risk analysis, disease testing and nutrition epidemiology](http://lib.dr.iastate.edu/etd/13380), Graduate Theses and Dissertations. Paper 13380. 

- Holtkamp D.J., **Lin H.**, Wang C, Polson D.D. (2013), [Evaluation of an objective risk scoring system for assessing the likelihood of virus introduction in porcine reproductive and respiratory syndrome virus-free breed-to-wean sow herds in the U.S.](http://www.scirp.org/journal/PaperInformation.aspx?PaperID=32700) Open Journal of Veterinary Medicine. 3 168-175.

- **Hui Lin**, Chong Wang, Peng Liu, Derald J. Holtkamp (2012), [Construction of Disease Risk Scoring Systems using Logistic Group Lasso: Application to Porcine Reproductive and Respiratory Syndrome Survey Data](http://www.tandfonline.com/doi/abs/10.1080/02664763.2012.752449), Journal of Applied Statistics. DOI:10.1080/02664763.2012.752449 
   
- Derald J. Holtkamp, **Hui Lin**, Chong Wang (2012), [Identifying questions in the American Association of Swine Veterinarian's PRRS risk assessment survey that are important for retrospectively classifying swine herds according to whether they reported clinical PRRS outbreaks in the previous 3 years.](http://www.ncbi.nlm.nih.gov/pubmed/22475927), Preventive Veterinary Medicine 106(2012) 42-52

- Allen, Kelli; Coetzee, Johann; Edwards-Callaway, Lily; Glynn, Hayley; Dockweiler, Jenna; KuKanich, Butch; **Lin, Hui**; Wang, Chong; Fraccaro, Elena; Jones, Meredyth; Bergamasco, Luciana (2012), [The impact and effect of timing of oral meloxicam administration on physiological responses in calves after dehorning with local anesthesia](http://www.journalofdairyscience.org/article/S0022-0302(13)00403-7/abstract), Journal of Dairy Science, DOI: http://dx.doi.org/10.3168/jds.2012-6251

- **Hui Lin**, Cheng Hao, Xiao Wang, Qiang Yuan, Tong-Jie Zhang, and Bao-Quan Wang (2008), [Observational H(z) Data as a complementary to other cosmological probes](http://www.worldscientific.com/doi/abs/10.1142/S0217732309030217), Modern Physics Letter A (No. MPLA-D-08-00168R1)


# Services and Professional Membership

- **2023 Chair**: ASA Section on Statistics in Marketing
- **Conference Committee**: [Annual Data Institute Conference 2019](https://www.sfdatainstitute.org)
- **2018 Program Chair**: ASA Section on Statistics in Marketing
- **2017 Program Chair-Elect**: ASA Section on Statistics in Marketing
- **2015-Present**, ASA Section on Statistics in Marketing
- **2011-Present**, American Statistical Association (ASA), member 
- **May 24-25, 2014**, Committee member, 7th R conference, Beijing, CHINA
- **2013-2014**, Chinese teacher, Iowa Chinese Language School (ICLS), Johnston, Iowa 
    - [ICLS](http://www.iowachineseschool.org/) is a non-profit and volunteer-based organization established on July 17, 1999.
