---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Hui Lin

fontawesome: yes
email: longqiman@gmail.com
github: happyrabbit
# phone: ""
web: scientistcafe.com
updated: no

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# TL;DR

- **Tech stack**: R, SQL, Python, bash, CSS, HTML
- **Industry experience**: Shopify (current), ex-Google, Netlify, DuPont
- **Role experience**:  Lead Quantitative Researcher (DS), Quantitative Researcher (UX), Data Science Manager, Marketing Data Scientist, Statistician

# Work and Research Experience

- **Sep.2021 - Present, Lead Quantitative Researcher, Shopify**, San Jose, CA, USA 
    1. Establish quantitative research as a discipline at Shopify
    2. Conduct foundational research on user perception (via surveys) and behavior (via logs) to inform product strategy and identify market opportunities.
    3. Work collaboratively in a multi-disciplinary team of statisticians, economists, social scientists, and designers to address complex long-term problems.
    
- **Jul.2020 - Sep.2021, Quantitative UX Researcher, Google**, Mountain View, CA, USA 
    1. Develop and implement a user-centered metric tracking framework.
    2. Identify product gaps, competitive positioning, and unmet user needs through a combination of large-scale surveys, text analytics, preference modeling, and log analysis.
    3. Collaborate with the machine intelligence team to develop innovative AI features.
    4. Drive change by communicating actionable findings to both experts and non-experts within the organization.

- **May.2018 - Jun.2020, Head of data science, Netlify**, San Francisco, CA, USA  
    1. Establish and manage a data science team to drive growth optimization and sales enablement. Netlify's user base has grown by over 15% per month, and revenue has grown by 10% per month.
    2. Collaborate with the infrastructure team to create data pipelines that centralize large-scale user-generated data (Data Lake) in a big data cloud environment.
    3. Develop and implement a Data Mart for business users.
    4. Define and oversee the development of user behavior analysis fundamentals.
 
- **May.2013 - Apr.2018, Marketing Data Scientist (Tech Lead), DuPont**, Johnston, IA, USA  
    1. Machine learning for predictive analytics.
    2. Analyzing marketing programs under observational scenarios.
    3. Conducting market research surveys.
    
# Education 

- PhD in Statistics, Department of Statistics, Iowa State University, USA
- MS in Statistics, Department of Statistics, Iowa State University, USA
- BS in Statistics, School of Mathematical Science, Beijing Normal University, CHINA

# Book 

- [Machine Learning using R](http://scientistcafe.com/book/): By Hui Lin
    - Publisher: Publishing House of Electronics industry
    - Status: Published in Oct 2017
    - ISBN : 9787121326585
    
- [Practitioner’s Guide to Data Science](https://www.routledge.com/Practitioners-Guide-to-Data-Science/Lin-Li/p/book/9780815354390): By Hui Lin and Ming Li
    - Publisher: CRC Press
    - Status: Published in May 2023
    - Github: https://github.com/happyrabbit/IntroDataScience
    
# Book Translation

- [Applied Predictive Modeling](http://appliedpredictivemodeling.com): By Max Kuhn and Kjell Johnson
    - Chinese translator for chapters 1-4, 12-14, 16, 18-20
    - Pubisher in China: Huazhang Publishing Inc.
    - Status: Published in May 2016

- [R for Marketing Research and Analytics](http://r-marketing.r-forge.r-project.org): By Chris Chapman and Elea McDonnell Feit
    - Chinese translator for the book
    - Pubisher in China: Huazhang Publishing Inc.
    - Status: Published in Oct 2016

- [Statistical Rethinking - A Bayesian Course with Examples in R and Stan](http://xcelab.net/rm/statistical-rethinking/): By Richard McElreath
    - Chinese translator for the book
    - Pubisher in China: Huazhang Publishing Inc.
    - Status: Published in Apr 2019

# Selected Tutorials and Talks

- [Data Science in Practice](https://course2022.scientistcafe.com/course-syllabus/), 2022-06-13, 2022 Quality and Productivity Research conference

- [User-centered metrics](https://scientistcafe.com/2021/07/14/usercenteredmetrics.html), 2021-07-01, invited by [HyVee](https://en.wikipedia.org/wiki/Hy-Vee) Analytics Team, [slides](https://scientistcafe.com/talks/2021_06usermetric/usermetric#/)

- [Introduction to Deep Learning (in R and Python)](https://smi2021.scientistcafe.com/)
    - 2021-05-17, The Statistical Methods in Imaging Conference 2021
- [Introduction to Data Science, Machine Learning and Deep Learning (in R and Python)](https://course2021.scientistcafe.com/course-syllabus/)
    - 2021-04-24, SCASA 40th Annual Applied Statistics Workshop
    - 2021-06-26, ASA Council of Chapters Traveling Course [Orange county-long beach]
    - 2021-07-23, ASA Council of Chapters Traveling Course [Nevada]
    - 2021-08-06, ASA Council of Chapters Traveling Course [Georgia]
    - 2021-08-20, ASA Council of Chapters Traveling Course [Columbus]
    - 2021-09-16, ASA Council of Chapters Traveling Course [Middle Tennessee]
    - 2021-10-09, ASA Council of Chapters Traveling Course [Boston]
    - 2021-10-23, ASA Council of Chapters Traveling Course [New York]
- Interactive document and dashboard using R and shiny, 2017-07-12,
[Central Iowa R User Group](http://www.meetup.com/Central-Iowa-R-User-Group/),
[Blog](http://scientistcafe.com/post/MarkdownReport.html)

- Data Scientist Using R - Data Wrangling, 2017-05-02, [Central Iowa R User Group](http://www.meetup.com/Central-Iowa-R-User-Group/), [Blog](http://scientistcafe.com/2017/04/30/DataWrangling.html)
