---
title: "Something about Riemann and Lebesgue intergals"
output: html_document
---

## 0.1 “Limit”——footstone of mathematical analysis
- In ``Group Theory'', the basic operation is $"\times"$, we define the kind of mapping which keeps the operation as : homomorphic mapping. It is a key mapping in Group Theory.

- In Mathematical Analysis, the foodstone is **limit** and the continuous functions are that keep **limit operation**, i.e.


$$if\ x_{n}\longrightarrow x\ \ \Rightarrow f(x_{n})\longrightarrow f(x)$$

So we can see the importance of continuous fuctions in Mathematical Analysis.

- Different definition of Continuous Functions:

Assume there are two metric space $(E,\ d)$ , and $(S,\ \rho)$.

$f:\ E\longrightarrow S$ then the following proposition are equivalent:

(a) The definition of continuous functtion that most of us learnt in Mathematical Analysis:


$$\forall\epsilon>0,\ \exists\delta>0,\ such\ that\ f(B_{d}(x_{0},\delta))\subset B_{\rho}(f(x_{0}),\epsilon)$$

> **Remark**: Most of us are used to the definition in $(R,\ d)$. However, it is only a case of metric space. Though it helps to understand by realine $R,$ or $R^{2}$, $R^{3}$......, metric space is much broader than that.


(b) $\forall G\subset S$, $G$ is open, we have $f^{-1}(G)=\{x\in E:\ f(x)\in G\}$
is open subset of $E$
(c) $\forall F\subset S$, $F$ is closed, we have $f^{-1}(F)=\{x\in E:\ f(x)\in F\}$
is closed subset of $E$

## 0.2 Riemann intergal and Lebesgue intergal

We learnt in **Mathematical Analysis** about Riemann intergal. In Measure Theory, there is another intergal called Lebesgue intergal. It is natural to ask : Why is Lebesgue intergal needed? 

1. Riemann intergal is partitioned by the **range** of function f; Lebesgue intergal is prtitioned by the **domain** of function f

It is like two persons are counting their money. What Mr. Riemann
does is: add the cashes one by one in order. What Mr. Lebesgue does
is: sort the cash, put cashes with the same value together then count
the number of \$100, number of \$50........ What Lebesgue does seems
to be more effective. 

2. Riemann intergable function space is not complete but the
sapce for Lebesgue intergable function is complete. i.e, the limitation
of a convergence sequence of **Riemann intergable functions** 
may not be **Riemann intergable**. But the
limitation of a convergence sequence of **Lebesgue intergable** is **Lebesgue intergable**.

3. Riemann intergal requires stronger precondition to interchange the order of **limitaion** and **integration** that is: uniform convergence. In Lebesgue, we only need ``Lebesgue\textquoteright{}s dominated convergence theorem (DCT)''

4. Let f be a bounded function on a bounded interval [a, b]. Then 

  - f is Riemann integrable on [a,b] iff f is continuous i.e (m) on [a, b]

**You need to show that: upper-Riemann intergral=lower-Riemann intergral**

Proof (to be cont)

  - f is Lebesgue integrable on [a, b] and the Lebesgue integral $\int_{[a,b]}fdm$ equals the Riemann integral $\oint_{[a,b]}f$, i.e., the two integrals coincide.

5. If f is Riemann absolute integrabe on an unbounded area $G$ and on every bounded subarea of $G$ is Riemann integrable, then f is Lebesgue integrable on $G$ and the two integrals are coincide.

**To show this, you need to use MCT and DCT**

For above $f(x_{1},x_{2},...,x_{n})$, Riemann absolute intergable is equivalent to Riemann intnergable when $n\geq2$}

## 0.3 Examples

$$f(x)=\begin{cases}
\begin{array}{cc}
1 & x\in Q\\
0 & x\in R/Q
\end{array}\end{cases}$$

$f(x)$ Legesbue integrable but not Riemann integrable}


