---
title: "Several properties of inverse CDF"
layout: post
time: '22:54'
---

We can use either sup or inf to define inverse CDF. The left/right
continuity of CDF is kind of confusing which depend on how you define
the CDF.


(1) $$F(x_{0})=P\{x:x<x_{0}\}$$

(2) $$F(x_{0})=P\{x:x\leq x_{0}\}$$


In the case of (1), the CDF is left continuous. In (2), the CDF is
right continuous. Here, we use (2) as the definition of CDF. 

The continunity for inverse CDF is even more tricky. For inf, we have
the following definition:

(3) $$F^{-1}(x)=inf\{x:F(x)>y\}$$

(4) $$F^{-1}(x)=inf\{x:F(x)\geq y\}$$

Similarly, we can use sup to define inverse CDF.

(5) $$F^{-1}(x)=sup\{x:F(x)<y\}$$


(6) $$F^{-1}(x)=sup\{x:F(x)\leq y\}$$


The following discussion is based on the definition (3) i.e.$F^{-1}(x)=sup\{x:F(x)<y\}$.
You can derivative properties in other cases.


### Prop1: $F^{-1}(y)$ is non-decreasing.


Assume $0<y_{1}<y_{2}<1$, because $F(x)$ is nondecreasing. Then we have

$$\{x:F(x)<y_{1}\}\subseteq\{x:F(x)<y_{2}\}$$


$$\Longleftrightarrow sup\{x:F(x)<y_{1}\}\leq sup\{x:F(x)<y_{2}\}$$

So $F^{-1}(y)$ is nondecreasing function.


### Prop2: $F(F^{-1}(y))\geq y$ and $"="$ holds when $F(x)$ is continuous at $F^{-1}(y)$. But $F(F^{-1}(y))= y$ doesn't mean $F(x)$ is continuous at $F^{-1}(y)$.

$H\equiv\{x:\ F(x)<y\}$

$F^{-1}(y)=sup\{x:\ F(x)<y\}=supH$

Here $F(x)\equiv P(\xi(\omega)\leq x)$ (right continuous)


- First show: $F(F^{-1}(y))\geq y$

For $\forall\epsilon>0$, $F^{-1}(y)+\epsilon\notin H$ then $F(F^{-1}(y)+\epsilon)\geq y$,
by the right continuity, 

$$\Longrightarrow lim_{\epsilon\rightarrow0}F(F^{-1}(y)+\epsilon)=F(F^{-1}(y))\geq y$$


- Then show $"="$ holds when $F(x)$ is continuous at $F^{-1}(y)$
i.e. $F(F^{-1}(y))=y$


$$\forall\epsilon>0,\ \exists x^{*}\ s,t,\ F^{-1}(y)-\epsilon<x^{*}\ and\ x^{*}\in H$$


Since $F^{-1}(y)$ is nondecreasing, 

$$F(F^{-1}(y)-\epsilon)\leq F(x^{*})<y$$



When $F(x)$ is continuous at $F^{-1}(y)$, 
$$F(F^{-1}(y)-\epsilon)\rightarrow F(F^{-1}(y))\ \ as\ \epsilon\rightarrow0$$
 


$$lim_{\epsilon\rightarrow0}F(F^{-1}(y)-\epsilon)=F(F^{-1}(y))\leq y$$



So $"="$ holds when $F(x)$ is continuous at $F^{-1}(y)$ i.e. $F(F^{-1}(y))=y$


### Prop3: $F^{-1}(F(x))\leq x$


For fixed $x_{0}$, assume $M=\{x:\ F(x)<F(x_{0})\}$, because $F(x)$
is nondecreasing, $\forall x\in M,\ \ x\leq x_{0}$. Since $F^{-1}(F(x_{0}))=supM$,
then $F^{-1}(F(x_{0}))\leq x_{0}$.


### Prop 4.1: $F^{-1}(y)\leq x \Longleftrightarrow y\leq F(x)$


### Prop 4.2: $F^{-1}(y)> x \Longleftrightarrow y>F(x)$



Only show 4.1

-  $"\Longleftarrow"$ 
$$F^{-1}(y)=sup\{x:\ F(x)<y\}$$



$$H=\{x:\ F(x)<y\}$$



If $y\leq F(x_{0})$ , $x_{0}\geq x\in H$ 

$$x_{0}\geq supH$$


- $"\Longrightarrow"$


If $F^{-1}(y)\leq x$, $y\leq F(F^{-1}(y))\leq F(x)$



### Prop5: $F^{-1}(y)$ is left continuous


$\forall y_{0}$ only need to show $lim_{y\rightarrow y_{0}^{-}}F^{-1}(y)\leq F^{-1}(y_{0})$


- First show that $lim_{y\rightarrow y_{0}^{-}}F^{-1}(y)\leq F^{-1}(y_{0})$
(obvious)
- Then show the other direction.

By Prop 4.1, only need to show $y_{0}\leq F(lim_{y\rightarrow y_{0}^{-}}F^{-1}(y))$


\[
F(lim_{y\rightarrow y_{0}^{-}}F^{-1}(y))\geq lim_{y\rightarrow y_{0}^{-}}F(F^{-1}(y))\geq lim_{y\rightarrow y_{0}^{-}}y=y_{0}
\]

