---
title: "PSM for Multiple Treatments"
author: "Hui Lin"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(readr)
library(MASS)
library(MatchIt)
library(optmatch)
library(ltm)
library(corrplot)
library(Matching)
library(rbounds)
library(rgenoud)
library(Zelig)
```

## Standard 

- Treatment group = 2: Use Propensity Score + Matching + t-test

- Treatment group >=3: Use Generalized Boosted Models + Weighting + Pairwise t-test
 
    - Use ATE
    
    - Use es.mean as stop.method
    
    - Use 5000 trees


---

## Last Time

- Types of research

- Power of randomization and the logic of hypothesis testing

- Types of statistical tests

- What is PSMs

- Matching overview

- Weighting

---

## What is PSMs?

- PSMs were coined by Rosenbaum and Rubin (1983a)

- Reduce selection bias through balancing the distributions of covariates between the treatment and comparison groups


- **Propensity Score** is the **probability** or **likelihood** of being assigned to the treatment group
   
    $p(\mathbf(X_i))=$ A linear combination of observed covariates


- Match, stratify or weigh on a single composite variable (i.e., propensity score) rather than multiple covariates


- PSMs can help design a non-RCT or observational study that approximates an RCT to make a more valid causal inference

---

## Clarification 1:  Three Steps

Step 1. Propensity Score

Step 2. Matching/Weighting

Step 3. Analysis

---

## Clarification 2:  ATE v.s. ATT

- Average Treatment Effect (ATE): comparison of mean outcomes had the entire population been observed under one treatment

- Average Treatment Effect Among the Treated (ATT): comparison, among study participants who were treated with $t'$, of their mean outcome when treated with treatment $t'$, as they were, with the mean outcome they would have had if they had instead been treated with treatment $t"$
    -  In the multiple treatments setting, the definition of ATT depends on what is meant by "the treated."

---

## Notations

- $i$: participant
- $z_i$: treatmennts ($z_i = 1...m$)
- $r_i$: outcome of interest
- $\mathbf{X_i}$: covariates
- $q$ : number of covariates

---


 ## GBM Propensity Score

- Iterative fitting algorithm: new tree is to provide the best fit to the residuals of the model from the previous iteration
- With enough iterations, the model is sufficiently flexible to perfectly fit the data
- Minimize an external criterion: imbalance on the covariates across the "treatment" and "control" groups

---

## Stopping Rules

- $SB_q = \frac{|\bar{X}_{q1}^{w}-\bar{X}_{q0}^{w}|}{\hat{\sigma}_q}$
    - <=0.2 small
    - 0.2~0.4 moderate
    - >= 0.4 large 
    - ASMD, absolute standardized bias or the effect size (ES)

- $KS_q = sup_\alpha|EDF_{1q}(\alpha) -EDF_{0k}(\alpha)|$
    - where $EDF_{mq}(\alpha) = \frac{\Sigma_{i=1}^n w_i I(z_i=m,\ X_{iq}\leq \alpha)}{\Sigma_{i=1}^{n}w_i I(z_i=m)}$
    - <= 0.1
    - Kolmogorov-Smirnov (KS)
     
---

## Weighting

- Directly incorporate propensity scores into outcome analysis with propensity score weighting

- For example, using inverse-probability-of-treatment-weighting (IPTW) in weighted regression

$$w_i = \frac{z_i}{p(\mathbf{X_i})} + \frac{1-z_i}{1-p(\mathbf{X_i})}$$ 

---

## Analysis: Using all the original data

- IPTW in weighted regression

$$r_i = \beta_0 + \beta_1 w_i + \beta_2 X_{i1}^* + \dots + \beta_{q+1}X_{iq}^* + \epsilon_i$$

$$\hat{ATE}=\hat{\beta}_1$$
with $w_i=\frac{z_i}{p(\mathbf{X_i})} + \frac{1-z_i}{1-p(\mathbf{X_i})}$

or 

$$\hat{ATT}=\hat{\beta_1}$$

with $w_i = z_i + \frac{(1-z_i)p(\mathbf{X_i})}{1-p(\mathbf{X_i})}$

---

## Analysis: Using all the original data

- Regression adjustment with propensity score as a covariate

$$r_i = \beta_0 + \beta_1 z_i + \beta_2 p(\mathbf{X_i})+\beta_3 z_i\times p(\mathbf{X_i})+\epsilon_i$$

$$\hat{ATE}=\hat{\beta_1}$$