---
title: "Propensity Score Weighting"
author: "Hui Lin"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(readr)
library(MASS)
library(MatchIt)
library(optmatch)
library(ltm)
library(corrplot)
library(Matching)
library(rbounds)
library(rgenoud)
```

## Different Methods 


- Matching: makes control participants similar to treated participants on propensity scores

- Subclassification: creates subclasses such that within a class or stratum, both treated and control participants are homogeneous on propensity scores

- Propensity score weighting: takes a different amount of information from each participant depending on the participant's conditional probability of receiving treatment. 

---

## Advantages

1. permits most types of multivariate outcome analyses and does not require an outcome variable that is continuous or normally distributed

2. permits retaining most study participants in the outcome analysis. Weighting does not sacrifice observations as greedy matching or trimming does.

> The method is analogous to the weighted analysis researchers typically conduct when analyzing data generated by a complex sampling design.

---

## Assumption

- Unconfoundedness: the treatment assignment is independent of the outcomes in both treated and control groups, conditional on the observed covariates, 

- The probability of assignment is bounded  away from 0 and 1
