
DATA MESSAGE_FID5;
	SET MESSAGE;
	IF FID=5;
	RUN;
DATA MESSAGE_FID6;
	SET MESSAGE;
	IF FID=6;
	RUN;
	DATA MESSAGE_FID7;
	SET MESSAGE;
	IF FID=7;
	RUN;
DATA MESSAGE_FID2;
	SET MESSAGE;
	IF FID=2;
	RUN;
DATA MESSAGE_FID3;
	SET MESSAGE;
	IF FID=3;
	RUN;
DATA MESSAGE_FID12;
	SET MESSAGE;
	IF FID=12;
	RUN;
DATA MESSAGE_FID14;
	SET MESSAGE;
	IF FID=14;
	RUN;
	DATA MESSAGE_FID15;
	SET MESSAGE;
	IF FID=15;
	RUN;

/*EXPORT DATA AS CSV*/
PROC EXPORT DATA = WORK.MESSAGE_FID2
	OUTFILE = "\\PHIBRED.COM\JH\MARKETING\MARKET ANALYSIS\MARKET ANALYSIS\NLP\RawData\MESSAGE_FID2.CSV"
	DBMS = CSV REPLACE;
/*	SHEET = "PC2013";*/
	RUN;
	PROC EXPORT DATA = WORK.MESSAGE_FID2
	OUTFILE = "C:\Users\linhu\Dropbox\NLP\RawData\MESSAGE_FID2.CSV"
	DBMS = CSV REPLACE;
/*	SHEET = "PC2013";*/
	RUN;